language: python
python:
  - "2.7"
before_install:
  - openssl aes-256-cbc -K $encrypted_2ae1a256cab0_key -iv $encrypted_2ae1a256cab0_iv
      -in buildconf/deploy/buildout-template-c3f13b4450c1.json.enc
      -out buildconf/deploy/buildout-template-c3f13b4450c1.json -d
  - sudo apt-get install xsltproc
  - mkdir build

install:
  - python bootstrap-buildout.py && ./bin/buildout
  - rm -rf parts/temp

script:
  - ./bin/nosetests --with-xunit --xunit-file=$PWD/nosetests.xml
  - xsltproc buildconf/nosetests.xslt nosetests.xml > build/nosetests.html

# todo: external script this and add coverage
after_success:
- ./travis-ci-deploy.sh

env:
  global:
    - secure: "Pg4bbTfcHe5cZHZM8sTitS685eCcHmyiOvfr9MSLjyAU4c8xob9iMHE2MyD1ZjAM8iVKliSUhYrJzUU4/3Q2gx6sAUK4n16Bp5f1nFxL+qrvRv5esnnXr/tQNIuZkuX6dwQxvz9Fb7LQxsSkLDJkjwsYxRH1bcJin6rU7fcmaPc="

cache:
  directories:
    - bin
    - eggs
    - downloads
    - src
    - google-cloud-sdk