language: python
python:
  - "2.7"


# --setuptools-version=8.3 is a hack until
# https://github.com/buildout/buildout/issues/237 is resolved?
install:
  - python bootstrap-buildout.py --setuptools-version=8.3 && ./bin/buildout

script:
  - ./bin/nosetests

after_success:
- echo "PR# $TRAVIS_PULL_REQUEST"
- echo $deploy_account
- printenv
- set -e